speckle:
  nscreens: 8
  original_res: 1024
    #datadirectory: /scratch/sciarella/males/MALES_Dataset1
  datadirectory: /home/simone/Dropbox/eScience_projects/MALES-project/8screens_1024x1024
preproc:
  #polresize: 2048
  polresize: 1024
  polarize: false
  equivariant: true
  randomrotate: false
  centercrop: 410
  resize: 256
  speckreps: 1
  dataname: all_images_test.pt
model:
  name: ModelCart
  type: resnet50
  save_every: 100
  pretrained: true
hyppar:
  maxepochs: 8
  batch_size: 32
  lr: 0.0001
  loss: MSELoss
  optimizer: Adam
