speckle:
  nscreens: 8
  original_res: 1024
  centercrop: 410
  resize: 256
  datadirectory: /home/simone/Dropbox/eScience_projects/MALES-project/8screens_1024x1024
model:
  name: resnet50
  save_every: 100
hyppar:
  maxepochs: 6
  batch_size: 32
  lr: 0.001
  loss: MSELoss
  optimizer: Adam
