speckle:
  nscreens: 8
  original_res: 1024
  datadirectory: /scratch/sciarella/males/MALES_Dataset1
preproc:
  polresize: 1024
  polarize: false
  equivariant: false
  randomrotate: false
  centercrop: 410
  resize: 256
  speckreps: 1
model:
  name: ModelCart
  type: resnet50
  save_every: 100
  pretrained: true
hyppar:
  maxepochs: 500
  batch_size: 64
  lr: 0.001
  loss: MSELoss
  optimizer: Adam
