speckle:
  nscreens: 8
  original_res: 1024
  centercrop: 410
  resize: 256
  speckreps: 15
  datadirectory: /scratch/sciarella/males/8screens_1024x1024
model:
  name: resnet50
  save_every: 100
hyppar:
  maxepochs: 200
  batch_size: 64
  lr: 0.001
  loss: MSELoss
  optimizer: Adam
