speckle:
  nscreens: 8
  original_res: 1024
  datadirectory: /scratch/sciarella/males/MALES_Dataset1
preproc:
  polresize: 1024
  polarize: false
  equivariant: false
  randomrotate: false
  centercrop: 410
  resize: 256
  speckreps: 1
  dataname: all_images_ModelCart.pt
model:
  name: ModelCart_18_noPretrain
  type: resnet18
  save_every: 100
  pretrained: false
hyppar:
  maxepochs: 1000
  batch_size: 64
  lr: 0.001
  loss: MSELoss
  optimizer: Adam
