speckle:
  nscreens: 8
  hArray: [0.1, 300, 650, 1e3, 2e3, 5e3, 10e3, 20e3, 40e3]
  splits: [150, 475, 825, 1500, 3500, 7500, 15000, 30000]
  lambda: 550
  z: 0
  L: 40e3
  original_res: 1024
  datadirectory: /scratch/sciarella/males/MALES_H5Dataset_2b3
preproc:
  polresize: 1024
  polarize: false
  equivariant: false
  randomrotate: false
  centercrop: -1
  resize: 256
  speckreps: 1
  ensemble: 3
  ensemble_unif: false
  normalization: lin
  dataname: all_images.pt
model:
  name: Model_res50_E3
  #name: Model_sc16
  #type: scnnC16
  type: resnet50
  save_every: 25
  pretrained: true
hyppar:
  maxepochs: 100
  ttsplit: 0.8
  batch_size: 32
  lr: 0.0001
  lr_scheduler: Plateau
  early_stopping: 50
  optimizer: Adam
loss:
  JMAE: 1 
  JMSE: 0
  Cn2MAE: 0 
  Cn2MSE: 0
  Pearson: 0
  Fried: 1
  Isoplanatic: 1
  Rytov: 0
  Scintillation_w: 1
  Scintillation_ms: 0
scnn:
  KERNEL_SIZES: [7, 7, 5, 5]
  PADDINGS: [1, 2, 2, 1]
  STRIDES: [1, 2, 2, 2]
  FEATURE_FIELDS: [24, 48, 48, 64]
  POOL_INDICES: [1, 3]
  SIGMA: [0.66, 0.66]
  POOL_STRIDES: [2, 2]
  POOL_PADDINGS: [0, 0]
  final_n_features: 32

