speckle:
  nscreens: 8
  original_res: 1024
  datadirectory: /scratch/sciarella/males/MALES_Dataset3
preproc:
  polresize: 1024
  polarize: false
  equivariant: false
  randomrotate: false
  centercrop: -1
  resize: 256
  speckreps: 1
  ensemble: 2
  ensemble_unif: false
  normalization: lin
  dataname: all_images.pt
model:
  name: Model_res50_E2
  #name: Model_sc16
  #type: scnnC16
  type: resnet50
  save_every: 25
  pretrained: true
hyppar:
  maxepochs: 100
  ttsplit: 0.8
  batch_size: 32
  lr: 0.0001
  loss: MSELoss
  optimizer: Adam
