speckle:
  nscreens: 8
  original_res: 1024
    #datadirectory: /scratch/sciarella/males/8screens_1024x1024
  datadirectory: /scratch/sciarella/males/MALES_Dataset1
  #datadirectory: /home/simone/Dropbox/eScience_projects/MALES-project/8screens_1024x1024
  #datadirectory: /home/simone/Dropbox/eScience_projects/MALES-project/MALES_Dataset1
preproc:
  #polresize: 2048
  polresize: 1024
  polarize: false
  equivariant: true
  randomrotate: false
  centercrop: 410
  resize: 256
  speckreps: 1
  multichannel: 1
  dataname: all_images_cart256.pt
model:
  name: Model_sC16
  type: small_scnnC16
  save_every: 10
  pretrained: true
hyppar:
  maxepochs: 300
  batch_size: 32
  lr: 0.0001
  loss: MSELoss
  optimizer: Adam
