speckle:
  nscreens: 8
  original_res: 1024
  datadirectory: /scratch/sciarella/males/MALES_Dataset3
preproc:
  polresize: 1024
  polarize: false
  equivariant: true
  randomrotate: false
  centercrop: 410
  resize: 256
  speckreps: 1
  ensemble: 1
  ensemble_unif: false
  normalization: lin
  dataname: all_images.pt
model:
  name: Model_res50_E1
  #name: Model_sc16
  #type: scnnC16
  type: resnet50
  save_every: 50
  pretrained: true
hyppar:
  maxepochs: 1
  ttsplit: 0.8
  batch_size: 64
  lr: 0.0001
  loss: MSELoss
  optimizer: Adam
