speckle:
  nscreens: 8
  hArray: [0.1, 300, 650, 1e3, 2e3, 5e3, 10e3, 20e3, 40e3]
  splits: [150, 475, 825, 1500, 3500, 7500, 15000, 30000]
  lambda: 550
  z: 0
  L: 40e3
  original_res: 108
  datadirectory: /scratch/sciarella/males/MALES_H5Dataset4
preproc:
  polresize: 108
  polarize: false
  equivariant: false
  randomrotate: false
  centercrop: -1
  resize: 108
  speckreps: 1
  ensemble: 1
  ensemble_unif: false
  normalization: lin
  img_normalization: false
  dataname: all_images.pt
noise:
  D: 1 # Fraction of field
  t: 0.01 # Width spider
  snr: 15 # Signal-to-noise ratio
  dT: 0.2 # Telescope diameter
  dO: 0.44 # fraction obscuration
  rn: 3.5 # random noise
  fw: 32e3 # full well capacity
  bit: 12 # bit level (sample depth)
  discretize: off # Whether to discretize the output ('on' or 'off').
model:
  name: Model_C6_deeperx2
  type: scnnC6
  save_every: 10
  pretrained: true
hyppar:
  maxepochs: 50
  ttsplit: 0.8
  batch_size: 32
  lr: 0.0001
  lr_scheduler: Plateau
  early_stopping: 50
  optimizer: Adam
loss:
  MAE: 0
  MSE: 1
  JMAE: 0 
  JMSE: 0
  Cn2MAE: 0 
  Cn2MSE: 0
  Pearson: 0
  Fried: 0
  Isoplanatic: 0
  Rytov: 0
  Scintillation_w: 0
  Scintillation_ms: 0
scnn:
  KERNEL_SIZES: [7, 5, 5, 5, 5, 5]
  PADDINGS: [1, 2, 2, 2, 2, 1]
  STRIDES: [1, 1, 1, 1, 1, 1]
  FEATURE_FIELDS: [8, 16, 32, 32, 64, 64]
  POOL_INDICES: [1, 3, 5 ]
  SIGMA: [0.66, 0.66, 0.66]
  POOL_STRIDES: [2, 2, 1]
  POOL_PADDINGS: [1, 1, 0]
final_block:
  - type: Dropout
    p: 0.2
  - type: Linear
    out_features: nscreens
  - type: Sigmoid
