speckle:
  nscreens: 8
  hArray: [0.1, 300, 650, 1e3, 2e3, 5e3, 10e3, 20e3, 40e3]
  splits: [150, 475, 825, 1500, 3500, 7500, 15000, 30000]
  lambda: 550
  z: 0
  L: 40e3
  original_res: 1024
  datadirectory: /scratch/sciarella/males/MALES_Dataset3_gscidar_1000
preproc:
  polresize: 1024
  polarize: false
  equivariant: false
  randomrotate: false
  centercrop: -1
  resize: 128
  speckreps: 1
  ensemble: 6
  ensemble_unif: false
  normalization: lin
  dataname: all_images.pt
model:
  name: Model_c6_E6_r_mae
  type: scnnC6
  save_every: 10
  pretrained: true
hyppar:
  maxepochs: 40
  ttsplit: 0.8
  batch_size: 32
  lr: 0.0001
  lr_scheduler: Plateau
  early_stopping: 50
  optimizer: Adam
loss:
  MAE: 0
  MSE: 1
  JMAE: 0 
  JMSE: 0
  Cn2MAE: 0 
  Cn2MSE: 0
  Pearson: 0
  Fried: 1
  Isoplanatic: 0
  Rytov: 0
  Scintillation_w: 0
  Scintillation_ms: 0
scnn:
  KERNEL_SIZES: [9, 7, 7, 7]
  PADDINGS: [2, 1, 1, 1]
  STRIDES: [2, 1, 1, 1]
  #PADDINGS: [2, 2, 2, 2]
  #STRIDES: [2, 2, 2, 2]
  FEATURE_FIELDS: [16, 32, 32, 32]
  #FEATURE_FIELDS: [32, 64, 64, 128]
  POOL_INDICES: [1, 3]
  SIGMA: [0.66, 0.66]
  POOL_STRIDES: [2, 2]
  POOL_PADDINGS: [0, 0]
  final_n_features: 32
  dropout_p: 0.2

